import { z } from 'zod';
import {
  PAYMENT_METHODS,
  SALES_CHANNELS,
  STAFF_ROLES,
  STOCK_MOVEMENT_REASONS,
} from './domain.js';

export const staffRoleSchema = z.enum(STAFF_ROLES);
export const stockMovementReasonSchema = z.enum(STOCK_MOVEMENT_REASONS);
export const paymentMethodSchema = z.enum(PAYMENT_METHODS);
export const salesChannelSchema = z.enum(SALES_CHANNELS);

const uuid = z.string().uuid();
const money = z.number().nonnegative().finite();

export const stockMovementInputSchema = z.object({
  variant_id: uuid,
  quantity_delta: z.number().int().refine((n) => n !== 0, 'quantity_delta cannot be zero'),
});
export type StockMovementInput = z.infer<typeof stockMovementInputSchema>;

export const recordMovementsSchema = z.object({
  location_id: uuid,
  reason: stockMovementReasonSchema,
  movements: z.array(stockMovementInputSchema).min(1).max(500),
  reference_type: z.string().max(64).nullish(),
  reference_id: z.string().max(128).nullish(),
  note: z.string().max(1000).nullish(),
});
export type RecordMovements = z.infer<typeof recordMovementsSchema>;

export const saleLineSchema = z.object({
  variant_id: uuid,
  quantity: z.number().int().positive().max(9999),
  /** Omit to use the variant's current price. Present for manual overrides. */
  unit_price_egp: money.optional(),
  discount_egp: money.default(0),
});
export type SaleLine = z.infer<typeof saleLineSchema>;

export const createStoreSaleSchema = z.object({
  location_id: uuid,
  payment_method: paymentMethodSchema,
  items: z.array(saleLineSchema).min(1).max(200),
  customer_id: uuid.nullish(),
  discount_egp: money.default(0),
  note: z.string().max(1000).nullish(),
  /**
   * Stable key generated by the client when the sale screen is opened. If the
   * phone loses signal mid-confirm and the cashier taps again, the second
   * request returns the first sale instead of selling the stock twice.
   */
  idempotency_key: z.string().min(8).max(128),
});
export type CreateStoreSale = z.infer<typeof createStoreSaleSchema>;

/** Egyptian mobile numbers, normalised to 01XXXXXXXXX. */
export function normalizeEgyptianPhone(input: string): string | null {
  const digits = input.replace(/\D/g, '');
  let local = digits;
  if (local.startsWith('0020')) local = local.slice(4);
  else if (local.startsWith('20') && local.length > 10) local = local.slice(2);
  if (!local.startsWith('0')) local = `0${local}`;
  return /^01[0125]\d{8}$/.test(local) ? local : null;
}

export const customerSchema = z.object({
  full_name: z.string().min(1).max(200).nullish(),
  phone: z
    .string()
    .transform((v, ctx) => {
      const normalized = normalizeEgyptianPhone(v);
      if (!normalized) {
        ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'invalid_egyptian_phone' });
        return z.NEVER;
      }
      return normalized;
    })
    .nullish(),
  email: z.string().email().nullish(),
  instagram_handle: z.string().max(100).nullish(),
  whatsapp_phone: z.string().max(32).nullish(),
});
export type CustomerInput = z.infer<typeof customerSchema>;
